spring:
  application:
    name: rocketmq-consumer
  dynamic:
    thread-pool:
      # 服务端地址
      server-addr: http://localhost:6691
      # 用户名
      username: admin
      # 密码
      password: 123456
      # 租户 id, 对应 tenant 表
      namespace: prescription
      # 项目 id, 对应 item 表
      item-id: ${spring.application.name}
rocketmq:
  consumer:
    # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    groupName: ${spring.application.name}
    # mq的nameserver地址
    namesrvAddr: 127.0.0.1:9876
    # 消费者线程数据量
    consumeThreadMin: 5
    consumeThreadMax: 32


